
//Set path to SmartSlog KP Library
#include <smartslog.h>

#ifndef _GENERATED_ONTOLOGY
#define	_GENERATED_ONTOLOGY


#ifdef	__cplusplus
extern "C" {
#endif


#define INCLUDE_ALL_ONT_ENTITIES 1
#ifdef INCLUDE_ALL_ONT_ENTITIES

#define INCLUDE_PROPERTY_HASLOCATION 1
#define INCLUDE_PROPERTY_HASPREFERENCESPOI 1
#define INCLUDE_PROPERTY_LASTDATE 1
#define INCLUDE_PROPERTY_USECULTURALINFO 1
#define INCLUDE_PROPERTY_ERANAME 1
#define INCLUDE_PROPERTY_CONTAINS 1
#define INCLUDE_PROPERTY_AGE 1
#define INCLUDE_PROPERTY_ISSTARTPOINT 1
#define INCLUDE_PROPERTY_ERRORMESSAGE 1
#define INCLUDE_PROPERTY_IMG 1
#define INCLUDE_PROPERTY_ERRORDESCRIPTION 1
#define INCLUDE_PROPERTY_RADIUS 1
#define INCLUDE_PROPERTY_FIRSTDATE 1
#define INCLUDE_PROPERTY_INREGION 1
#define INCLUDE_PROPERTY_ACTIONTITLE 1
#define INCLUDE_PROPERTY_PREFERTRIPTYPE 1
#define INCLUDE_PROPERTY_POITITLE 1
#define INCLUDE_PROPERTY_ERRORCODE 1
#define INCLUDE_PROPERTY_MBOX 1
#define INCLUDE_PROPERTY_HASCLIMATERESTRICTION 1
#define INCLUDE_PROPERTY_START 1
#define INCLUDE_PROPERTY_LOGIN 1
#define INCLUDE_PROPERTY_STARTTIME 1
#define INCLUDE_PROPERTY_LOCATEDAT 1
#define INCLUDE_PROPERTY_USEUSERPREFERENCES 1
#define INCLUDE_PROPERTY_PHOTOHASLOCATION 1
#define INCLUDE_PROPERTY_DESCRIPTION 1
#define INCLUDE_PROPERTY_UID 1
#define INCLUDE_PROPERTY_USETRIPTYPE 1
#define INCLUDE_PROPERTY_HASHOMETOWN 1
#define INCLUDE_PROPERTY_PROVIDE 1
#define INCLUDE_PROPERTY_HASFAVORITEPOINT 1
#define INCLUDE_PROPERTY_LAT 1
#define INCLUDE_PROPERTY_ISENDPOINT 1
#define INCLUDE_PROPERTY_BELONGTO 1
#define INCLUDE_PROPERTY_WIDTH 1
#define INCLUDE_PROPERTY_METEOCONDITIONS 1
#define INCLUDE_PROPERTY_END 1
#define INCLUDE_PROPERTY_AUTHOR 1
#define INCLUDE_PROPERTY_HASMOVEMENT 1
#define INCLUDE_PROPERTY_ADDRESS 1
#define INCLUDE_PROPERTY_PROFESSION 1
#define INCLUDE_PROPERTY_TEMPERATURE 1
#define INCLUDE_PROPERTY_ENDTIME 1
#define INCLUDE_PROPERTY_POICATEGORY 1
#define INCLUDE_PROPERTY_HASVISITTIMERESTRICTIONS 1
#define INCLUDE_PROPERTY_VISITDURATION 1
#define INCLUDE_PROPERTY_HASACTION 1
#define INCLUDE_PROPERTY_DATEOFBIRTH 1
#define INCLUDE_PROPERTY_PHONE 1
#define INCLUDE_PROPERTY_URL 1
#define INCLUDE_PROPERTY_HEIGHT 1
#define INCLUDE_PROPERTY_NAME 1
#define INCLUDE_PROPERTY_CREATIONDATE 1
#define INCLUDE_PROPERTY_WEATHERSEASON 1
#define INCLUDE_PROPERTY_ARCHITECTURALSTYLE 1
#define INCLUDE_PROPERTY_HASPHOTO 1
#define INCLUDE_PROPERTY_RELATEDWITHPERSON 1
#define INCLUDE_PROPERTY_HASCULTURALINFO 1
#define INCLUDE_PROPERTY_LONG 1
#define INCLUDE_PROPERTY_USELOCATION 1
#define INCLUDE_PROPERTY_HASVISITPOINT 1
#define INCLUDE_PROPERTY_RATING 1
#define INCLUDE_PROPERTY_PASSWORD 1
#define INCLUDE_PROPERTY_LENGTH 1
#define INCLUDE_CLASS_WALKROAD 1
#define INCLUDE_CLASS_GEOGRAPHICALREGION 1
#define INCLUDE_CLASS_POINT 1
#define INCLUDE_CLASS_ACCOMODATION 1
#define INCLUDE_CLASS_ERA 1
#define INCLUDE_CLASS_ROUTE 1
#define INCLUDE_CLASS_CARROAD 1
#define INCLUDE_CLASS_ADMINISTRATIVEREGION 1
#define INCLUDE_CLASS_THING 1
#define INCLUDE_CLASS_SCHEDULE 1
#define INCLUDE_CLASS_TRIPTYPE 1
#define INCLUDE_CLASS_CLIMATE 1
#define INCLUDE_CLASS_VISITTIME 1
#define INCLUDE_CLASS_PITSTOP 1
#define INCLUDE_CLASS_POI 1
#define INCLUDE_CLASS_CULTURALINFO 1
#define INCLUDE_CLASS_ROAD 1
#define INCLUDE_CLASS_NOTHING 1
#define INCLUDE_CLASS_PHOTO 1
#define INCLUDE_CLASS_USER 1
#define INCLUDE_CLASS_SEARCHREQUEST 1
#define INCLUDE_CLASS_ACTION 1
#define INCLUDE_CLASS_PERSON 1
#define INCLUDE_CLASS_MOVEMENT 1
#define INCLUDE_CLASS_CIRCLEREGION 1
#define INCLUDE_CLASS_BUSROAD 1
#define INCLUDE_CLASS_ERROR 1
#define INCLUDE_CLASS_RAILROAD 1
#define INCLUDE_CLASS_REGION 1
#define INCLUDE_CLASS_LOCATION 1
#define INCLUDE_CLASS_AIRROAD 1
#define INCLUDE_CLASS_RECTANGULARREGION 1


#else

#define INCLUDE_PROPERTY_HASLOCATION 0
#define INCLUDE_PROPERTY_HASPREFERENCESPOI 0
#define INCLUDE_PROPERTY_LASTDATE 0
#define INCLUDE_PROPERTY_USECULTURALINFO 0
#define INCLUDE_PROPERTY_ERANAME 0
#define INCLUDE_PROPERTY_CONTAINS 0
#define INCLUDE_PROPERTY_AGE 0
#define INCLUDE_PROPERTY_ISSTARTPOINT 0
#define INCLUDE_PROPERTY_ERRORMESSAGE 0
#define INCLUDE_PROPERTY_IMG 0
#define INCLUDE_PROPERTY_ERRORDESCRIPTION 0
#define INCLUDE_PROPERTY_RADIUS 0
#define INCLUDE_PROPERTY_FIRSTDATE 0
#define INCLUDE_PROPERTY_INREGION 0
#define INCLUDE_PROPERTY_ACTIONTITLE 0
#define INCLUDE_PROPERTY_PREFERTRIPTYPE 0
#define INCLUDE_PROPERTY_POITITLE 0
#define INCLUDE_PROPERTY_ERRORCODE 0
#define INCLUDE_PROPERTY_MBOX 0
#define INCLUDE_PROPERTY_HASCLIMATERESTRICTION 0
#define INCLUDE_PROPERTY_START 0
#define INCLUDE_PROPERTY_LOGIN 0
#define INCLUDE_PROPERTY_STARTTIME 0
#define INCLUDE_PROPERTY_LOCATEDAT 0
#define INCLUDE_PROPERTY_USEUSERPREFERENCES 0
#define INCLUDE_PROPERTY_PHOTOHASLOCATION 0
#define INCLUDE_PROPERTY_DESCRIPTION 0
#define INCLUDE_PROPERTY_UID 0
#define INCLUDE_PROPERTY_USETRIPTYPE 0
#define INCLUDE_PROPERTY_HASHOMETOWN 0
#define INCLUDE_PROPERTY_PROVIDE 0
#define INCLUDE_PROPERTY_HASFAVORITEPOINT 0
#define INCLUDE_PROPERTY_LAT 0
#define INCLUDE_PROPERTY_ISENDPOINT 0
#define INCLUDE_PROPERTY_BELONGTO 0
#define INCLUDE_PROPERTY_WIDTH 0
#define INCLUDE_PROPERTY_METEOCONDITIONS 0
#define INCLUDE_PROPERTY_END 0
#define INCLUDE_PROPERTY_AUTHOR 0
#define INCLUDE_PROPERTY_HASMOVEMENT 0
#define INCLUDE_PROPERTY_ADDRESS 0
#define INCLUDE_PROPERTY_PROFESSION 0
#define INCLUDE_PROPERTY_TEMPERATURE 0
#define INCLUDE_PROPERTY_ENDTIME 0
#define INCLUDE_PROPERTY_POICATEGORY 0
#define INCLUDE_PROPERTY_HASVISITTIMERESTRICTIONS 0
#define INCLUDE_PROPERTY_VISITDURATION 0
#define INCLUDE_PROPERTY_HASACTION 0
#define INCLUDE_PROPERTY_DATEOFBIRTH 0
#define INCLUDE_PROPERTY_PHONE 0
#define INCLUDE_PROPERTY_URL 0
#define INCLUDE_PROPERTY_HEIGHT 0
#define INCLUDE_PROPERTY_NAME 0
#define INCLUDE_PROPERTY_CREATIONDATE 0
#define INCLUDE_PROPERTY_WEATHERSEASON 0
#define INCLUDE_PROPERTY_ARCHITECTURALSTYLE 0
#define INCLUDE_PROPERTY_HASPHOTO 0
#define INCLUDE_PROPERTY_RELATEDWITHPERSON 0
#define INCLUDE_PROPERTY_HASCULTURALINFO 0
#define INCLUDE_PROPERTY_LONG 0
#define INCLUDE_PROPERTY_USELOCATION 0
#define INCLUDE_PROPERTY_HASVISITPOINT 0
#define INCLUDE_PROPERTY_RATING 0
#define INCLUDE_PROPERTY_PASSWORD 0
#define INCLUDE_PROPERTY_LENGTH 0
#define INCLUDE_CLASS_WALKROAD 0
#define INCLUDE_CLASS_GEOGRAPHICALREGION 0
#define INCLUDE_CLASS_POINT 0
#define INCLUDE_CLASS_ACCOMODATION 0
#define INCLUDE_CLASS_ERA 0
#define INCLUDE_CLASS_ROUTE 0
#define INCLUDE_CLASS_CARROAD 0
#define INCLUDE_CLASS_ADMINISTRATIVEREGION 0
#define INCLUDE_CLASS_THING 0
#define INCLUDE_CLASS_SCHEDULE 0
#define INCLUDE_CLASS_TRIPTYPE 0
#define INCLUDE_CLASS_CLIMATE 0
#define INCLUDE_CLASS_VISITTIME 0
#define INCLUDE_CLASS_PITSTOP 0
#define INCLUDE_CLASS_POI 0
#define INCLUDE_CLASS_CULTURALINFO 0
#define INCLUDE_CLASS_ROAD 0
#define INCLUDE_CLASS_NOTHING 0
#define INCLUDE_CLASS_PHOTO 0
#define INCLUDE_CLASS_USER 0
#define INCLUDE_CLASS_SEARCHREQUEST 0
#define INCLUDE_CLASS_ACTION 0
#define INCLUDE_CLASS_PERSON 0
#define INCLUDE_CLASS_MOVEMENT 0
#define INCLUDE_CLASS_CIRCLEREGION 0
#define INCLUDE_CLASS_BUSROAD 0
#define INCLUDE_CLASS_ERROR 0
#define INCLUDE_CLASS_RAILROAD 0
#define INCLUDE_CLASS_REGION 0
#define INCLUDE_CLASS_LOCATION 0
#define INCLUDE_CLASS_AIRROAD 0
#define INCLUDE_CLASS_RECTANGULARREGION 0


#endif


#if INCLUDE_CLASS_WALKROAD
extern sslog_class_t *CLASS_WALKROAD;
#endif
#if INCLUDE_CLASS_GEOGRAPHICALREGION
extern sslog_class_t *CLASS_GEOGRAPHICALREGION;
#endif
#if INCLUDE_CLASS_POINT
extern sslog_class_t *CLASS_POINT;
#endif
#if INCLUDE_CLASS_ACCOMODATION
extern sslog_class_t *CLASS_ACCOMODATION;
#endif
#if INCLUDE_CLASS_ERA
extern sslog_class_t *CLASS_ERA;
#endif
#if INCLUDE_CLASS_ROUTE
extern sslog_class_t *CLASS_ROUTE;
#endif
#if INCLUDE_CLASS_CARROAD
extern sslog_class_t *CLASS_CARROAD;
#endif
#if INCLUDE_CLASS_ADMINISTRATIVEREGION
extern sslog_class_t *CLASS_ADMINISTRATIVEREGION;
#endif
#if INCLUDE_CLASS_THING
extern sslog_class_t *CLASS_THING;
#endif
#if INCLUDE_CLASS_SCHEDULE
extern sslog_class_t *CLASS_SCHEDULE;
#endif
#if INCLUDE_CLASS_TRIPTYPE
extern sslog_class_t *CLASS_TRIPTYPE;
#endif
#if INCLUDE_CLASS_CLIMATE
extern sslog_class_t *CLASS_CLIMATE;
#endif
#if INCLUDE_CLASS_VISITTIME
extern sslog_class_t *CLASS_VISITTIME;
#endif
#if INCLUDE_CLASS_PITSTOP
extern sslog_class_t *CLASS_PITSTOP;
#endif
#if INCLUDE_CLASS_POI
extern sslog_class_t *CLASS_POI;
#endif
#if INCLUDE_CLASS_CULTURALINFO
extern sslog_class_t *CLASS_CULTURALINFO;
#endif
#if INCLUDE_CLASS_ROAD
extern sslog_class_t *CLASS_ROAD;
#endif
#if INCLUDE_CLASS_NOTHING
extern sslog_class_t *CLASS_NOTHING;
#endif
#if INCLUDE_CLASS_PHOTO
extern sslog_class_t *CLASS_PHOTO;
#endif
#if INCLUDE_CLASS_USER
extern sslog_class_t *CLASS_USER;
#endif
#if INCLUDE_CLASS_SEARCHREQUEST
extern sslog_class_t *CLASS_SEARCHREQUEST;
#endif
#if INCLUDE_CLASS_ACTION
extern sslog_class_t *CLASS_ACTION;
#endif
#if INCLUDE_CLASS_PERSON
extern sslog_class_t *CLASS_PERSON;
#endif
#if INCLUDE_CLASS_MOVEMENT
extern sslog_class_t *CLASS_MOVEMENT;
#endif
#if INCLUDE_CLASS_CIRCLEREGION
extern sslog_class_t *CLASS_CIRCLEREGION;
#endif
#if INCLUDE_CLASS_BUSROAD
extern sslog_class_t *CLASS_BUSROAD;
#endif
#if INCLUDE_CLASS_ERROR
extern sslog_class_t *CLASS_ERROR;
#endif
#if INCLUDE_CLASS_RAILROAD
extern sslog_class_t *CLASS_RAILROAD;
#endif
#if INCLUDE_CLASS_REGION
extern sslog_class_t *CLASS_REGION;
#endif
#if INCLUDE_CLASS_LOCATION
extern sslog_class_t *CLASS_LOCATION;
#endif
#if INCLUDE_CLASS_AIRROAD
extern sslog_class_t *CLASS_AIRROAD;
#endif
#if INCLUDE_CLASS_RECTANGULARREGION
extern sslog_class_t *CLASS_RECTANGULARREGION;
#endif


#if INCLUDE_PROPERTY_HASLOCATION
extern sslog_property_t *PROPERTY_HASLOCATION;
#endif
#if INCLUDE_PROPERTY_HASPREFERENCESPOI
extern sslog_property_t *PROPERTY_HASPREFERENCESPOI;
#endif
#if INCLUDE_PROPERTY_LASTDATE
extern sslog_property_t *PROPERTY_LASTDATE;
#endif
#if INCLUDE_PROPERTY_USECULTURALINFO
extern sslog_property_t *PROPERTY_USECULTURALINFO;
#endif
#if INCLUDE_PROPERTY_ERANAME
extern sslog_property_t *PROPERTY_ERANAME;
#endif
#if INCLUDE_PROPERTY_CONTAINS
extern sslog_property_t *PROPERTY_CONTAINS;
#endif
#if INCLUDE_PROPERTY_AGE
extern sslog_property_t *PROPERTY_AGE;
#endif
#if INCLUDE_PROPERTY_ISSTARTPOINT
extern sslog_property_t *PROPERTY_ISSTARTPOINT;
#endif
#if INCLUDE_PROPERTY_ERRORMESSAGE
extern sslog_property_t *PROPERTY_ERRORMESSAGE;
#endif
#if INCLUDE_PROPERTY_IMG
extern sslog_property_t *PROPERTY_IMG;
#endif
#if INCLUDE_PROPERTY_ERRORDESCRIPTION
extern sslog_property_t *PROPERTY_ERRORDESCRIPTION;
#endif
#if INCLUDE_PROPERTY_RADIUS
extern sslog_property_t *PROPERTY_RADIUS;
#endif
#if INCLUDE_PROPERTY_FIRSTDATE
extern sslog_property_t *PROPERTY_FIRSTDATE;
#endif
#if INCLUDE_PROPERTY_INREGION
extern sslog_property_t *PROPERTY_INREGION;
#endif
#if INCLUDE_PROPERTY_ACTIONTITLE
extern sslog_property_t *PROPERTY_ACTIONTITLE;
#endif
#if INCLUDE_PROPERTY_PREFERTRIPTYPE
extern sslog_property_t *PROPERTY_PREFERTRIPTYPE;
#endif
#if INCLUDE_PROPERTY_POITITLE
extern sslog_property_t *PROPERTY_POITITLE;
#endif
#if INCLUDE_PROPERTY_ERRORCODE
extern sslog_property_t *PROPERTY_ERRORCODE;
#endif
#if INCLUDE_PROPERTY_MBOX
extern sslog_property_t *PROPERTY_MBOX;
#endif
#if INCLUDE_PROPERTY_HASCLIMATERESTRICTION
extern sslog_property_t *PROPERTY_HASCLIMATERESTRICTION;
#endif
#if INCLUDE_PROPERTY_START
extern sslog_property_t *PROPERTY_START;
#endif
#if INCLUDE_PROPERTY_LOGIN
extern sslog_property_t *PROPERTY_LOGIN;
#endif
#if INCLUDE_PROPERTY_STARTTIME
extern sslog_property_t *PROPERTY_STARTTIME;
#endif
#if INCLUDE_PROPERTY_LOCATEDAT
extern sslog_property_t *PROPERTY_LOCATEDAT;
#endif
#if INCLUDE_PROPERTY_USEUSERPREFERENCES
extern sslog_property_t *PROPERTY_USEUSERPREFERENCES;
#endif
#if INCLUDE_PROPERTY_PHOTOHASLOCATION
extern sslog_property_t *PROPERTY_PHOTOHASLOCATION;
#endif
#if INCLUDE_PROPERTY_DESCRIPTION
extern sslog_property_t *PROPERTY_DESCRIPTION;
#endif
#if INCLUDE_PROPERTY_UID
extern sslog_property_t *PROPERTY_UID;
#endif
#if INCLUDE_PROPERTY_USETRIPTYPE
extern sslog_property_t *PROPERTY_USETRIPTYPE;
#endif
#if INCLUDE_PROPERTY_HASHOMETOWN
extern sslog_property_t *PROPERTY_HASHOMETOWN;
#endif
#if INCLUDE_PROPERTY_PROVIDE
extern sslog_property_t *PROPERTY_PROVIDE;
#endif
#if INCLUDE_PROPERTY_HASFAVORITEPOINT
extern sslog_property_t *PROPERTY_HASFAVORITEPOINT;
#endif
#if INCLUDE_PROPERTY_LAT
extern sslog_property_t *PROPERTY_LAT;
#endif
#if INCLUDE_PROPERTY_ISENDPOINT
extern sslog_property_t *PROPERTY_ISENDPOINT;
#endif
#if INCLUDE_PROPERTY_BELONGTO
extern sslog_property_t *PROPERTY_BELONGTO;
#endif
#if INCLUDE_PROPERTY_WIDTH
extern sslog_property_t *PROPERTY_WIDTH;
#endif
#if INCLUDE_PROPERTY_METEOCONDITIONS
extern sslog_property_t *PROPERTY_METEOCONDITIONS;
#endif
#if INCLUDE_PROPERTY_END
extern sslog_property_t *PROPERTY_END;
#endif
#if INCLUDE_PROPERTY_AUTHOR
extern sslog_property_t *PROPERTY_AUTHOR;
#endif
#if INCLUDE_PROPERTY_HASMOVEMENT
extern sslog_property_t *PROPERTY_HASMOVEMENT;
#endif
#if INCLUDE_PROPERTY_ADDRESS
extern sslog_property_t *PROPERTY_ADDRESS;
#endif
#if INCLUDE_PROPERTY_PROFESSION
extern sslog_property_t *PROPERTY_PROFESSION;
#endif
#if INCLUDE_PROPERTY_TEMPERATURE
extern sslog_property_t *PROPERTY_TEMPERATURE;
#endif
#if INCLUDE_PROPERTY_ENDTIME
extern sslog_property_t *PROPERTY_ENDTIME;
#endif
#if INCLUDE_PROPERTY_POICATEGORY
extern sslog_property_t *PROPERTY_POICATEGORY;
#endif
#if INCLUDE_PROPERTY_HASVISITTIMERESTRICTIONS
extern sslog_property_t *PROPERTY_HASVISITTIMERESTRICTIONS;
#endif
#if INCLUDE_PROPERTY_VISITDURATION
extern sslog_property_t *PROPERTY_VISITDURATION;
#endif
#if INCLUDE_PROPERTY_HASACTION
extern sslog_property_t *PROPERTY_HASACTION;
#endif
#if INCLUDE_PROPERTY_DATEOFBIRTH
extern sslog_property_t *PROPERTY_DATEOFBIRTH;
#endif
#if INCLUDE_PROPERTY_PHONE
extern sslog_property_t *PROPERTY_PHONE;
#endif
#if INCLUDE_PROPERTY_URL
extern sslog_property_t *PROPERTY_URL;
#endif
#if INCLUDE_PROPERTY_HEIGHT
extern sslog_property_t *PROPERTY_HEIGHT;
#endif
#if INCLUDE_PROPERTY_NAME
extern sslog_property_t *PROPERTY_NAME;
#endif
#if INCLUDE_PROPERTY_CREATIONDATE
extern sslog_property_t *PROPERTY_CREATIONDATE;
#endif
#if INCLUDE_PROPERTY_WEATHERSEASON
extern sslog_property_t *PROPERTY_WEATHERSEASON;
#endif
#if INCLUDE_PROPERTY_ARCHITECTURALSTYLE
extern sslog_property_t *PROPERTY_ARCHITECTURALSTYLE;
#endif
#if INCLUDE_PROPERTY_HASPHOTO
extern sslog_property_t *PROPERTY_HASPHOTO;
#endif
#if INCLUDE_PROPERTY_RELATEDWITHPERSON
extern sslog_property_t *PROPERTY_RELATEDWITHPERSON;
#endif
#if INCLUDE_PROPERTY_HASCULTURALINFO
extern sslog_property_t *PROPERTY_HASCULTURALINFO;
#endif
#if INCLUDE_PROPERTY_LONG
extern sslog_property_t *PROPERTY_LONG;
#endif
#if INCLUDE_PROPERTY_USELOCATION
extern sslog_property_t *PROPERTY_USELOCATION;
#endif
#if INCLUDE_PROPERTY_HASVISITPOINT
extern sslog_property_t *PROPERTY_HASVISITPOINT;
#endif
#if INCLUDE_PROPERTY_RATING
extern sslog_property_t *PROPERTY_RATING;
#endif
#if INCLUDE_PROPERTY_PASSWORD
extern sslog_property_t *PROPERTY_PASSWORD;
#endif
#if INCLUDE_PROPERTY_LENGTH
extern sslog_property_t *PROPERTY_LENGTH;
#endif



void register_ontology();

	
#ifdef	__cplusplus
}
#endif

#endif /* _GENERATED_ONTOLOGY */
