#ifndef CAPTGENERATOR_GLOBAL_H
#define CAPTGENERATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CAPTGENERATOR_LIBRARY)
#  define CAPTGENERATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CAPTGENERATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CAPTGENERATOR_GLOBAL_H
